export const styles: Record<string, React.CSSProperties> = {
  page: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(360px, 1fr))",
    minHeight: "100vh",
    fontFamily: "'DM Sans', sans-serif",
    background: "#F6F2ED",
  },
  left: {
    background: "#7B1E1E",
    backgroundImage:
      "radial-gradient(circle at 15% 20%, rgba(255,255,255,0.12) 0, rgba(255,255,255,0) 45%), linear-gradient(135deg, #922B21 0%, #7B1E1E 55%, #5D1515 100%)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "clamp(1.5rem, 4vw, 3rem)",
    position: "relative",
    overflow: "hidden",
  },
  leftInner: {
    display: "flex",
    flexDirection: "column",
    gap: "3rem",
    position: "relative",
    zIndex: 1,
  },
  logo: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  logoIcon: {
    width: "36px",
    height: "36px",
    background: "rgba(255,255,255,0.15)",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "20px",
    color: "white",
    fontWeight: 700,
  },
  hero: { maxWidth: "340px" },
  heroTag: {
    display: "inline-block",
    background: "rgba(255,255,255,0.12)",
    color: "rgba(255,255,255,0.8)",
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "1.5px",
    textTransform: "uppercase",
    padding: "6px 12px",
    borderRadius: "20px",
    marginBottom: "1.2rem",
  },
  heroTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "2.4rem",
    lineHeight: 1.2,
    color: "white",
    fontWeight: 700,
    marginBottom: "1rem",
  },
  heroDesc: {
    color: "rgba(255,255,255,0.6)",
    fontSize: "15px",
    lineHeight: 1.7,
    fontWeight: 300,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "10px",
  },
  statCard: {
    background: "rgba(255,255,255,0.07)",
    border: "0.5px solid rgba(255,255,255,0.12)",
    borderRadius: "12px",
    padding: "0.9rem 1.1rem",
  },
  statNum: {
    fontSize: "1.5rem",
    fontWeight: 600,
    color: "white",
    fontFamily: "'Playfair Display', serif",
  },
  statLabel: {
    fontSize: "12px",
    color: "rgba(255,255,255,0.5)",
    marginTop: "2px",
  },
  right: {
    background: "linear-gradient(180deg, #FCFAF7 0%, #F7F2EC 100%)",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    padding: "clamp(1.25rem, 4vw, 3rem)",
  },
  rightInner: {
    maxWidth: "560px",
    width: "100%",
    margin: "0 auto",
    padding: "clamp(1rem, 3vw, 2rem)",
    background: "rgba(255,255,255,0.92)",
    borderRadius: "18px",
    border: "1px solid #F0E3D8",
    boxShadow: "0 16px 40px rgba(60, 26, 18, 0.12)",
    backdropFilter: "blur(6px)",
  },
  formTitle: {
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.9rem",
    fontWeight: 700,
    color: "#1A1A1A",
    marginBottom: "4px",
  },
  formSub: {
    color: "#888",
    fontSize: "14px",
  },
  link: {
    color: "#C0392B",
    textDecoration: "none",
    fontWeight: 500,
  },
  steps: {
    display: "flex",
    alignItems: "center",
    marginBottom: "1.8rem",
    flexWrap: "wrap",
    rowGap: "10px",
    columnGap: "6px",
  },
  stepNum: {
    width: "28px",
    height: "28px",
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "12px",
    fontWeight: 500,
    border: "1.5px solid",
    transition: "all 0.2s",
    flexShrink: 0,
  },
  section: {
    animation: "fadeIn 0.25s ease",
  },
  sectionTitle: {
    fontSize: "11px",
    fontWeight: 500,
    letterSpacing: "1px",
    textTransform: "uppercase" as const,
    color: "#C0392B",
    marginBottom: "1rem",
  },
  grid2: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  },
  grid3: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: "14px",
  },
  label: {
    fontSize: "12px",
    fontWeight: 500,
    color: "#777",
    letterSpacing: "0.3px",
  },
  input: {
    width: "100%",
    height: "40px",
    padding: "0 12px",
    background: "#F9F6F1",
    border: "1px solid #E8E2DA",
    borderRadius: "8px",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "14px",
    color: "#1A1A1A",
    outline: "none",
    boxSizing: "border-box" as const,
    transition: "border-color 0.2s ease, box-shadow 0.2s ease",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.7)",
  },
  inputError: {
    borderColor: "#E74C3C",
  },
  errorText: {
    fontSize: "11px",
    color: "#C0392B",
  },
  hint: {
    fontSize: "11px",
    color: "#999",
    marginTop: "2px",
  },
  selectBtn: {
    height: "40px",
    border: "1px solid",
    borderRadius: "8px",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
    boxShadow: "0 6px 14px rgba(28, 16, 12, 0.08)",
  },
  detectBtn: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "#FADBD8",
    border: "1px solid #F5A9A3",
    borderRadius: "8px",
    padding: "0 16px",
    height: "36px",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "13px",
    fontWeight: 500,
    color: "#C0392B",
    cursor: "pointer",
    marginBottom: "1rem",
  },
  socialField: {
    display: "flex",
    alignItems: "center",
    border: "1px solid #E8E2DA",
    borderRadius: "8px",
    overflow: "hidden",
    background: "#F7F5F2",
    marginTop: "5px",
  },
  socialPrefix: {
    padding: "0 12px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    fontSize: "12px",
    color: "#888",
    borderRight: "1px solid #E8E2DA",
    background: "white",
    whiteSpace: "nowrap" as const,
    flexShrink: 0,
  },
  socialInput: {
    border: "none",
    borderRadius: "0",
    height: "40px",
    background: "transparent",
    flex: 1,
    padding: "0 12px",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "14px",
    color: "#1A1A1A",
    outline: "none",
    width: "100%",
  },
  infoBox: {
    background: "#FEF9F0",
    border: "1px solid #F9C74F",
    borderRadius: "10px",
    padding: "12px 14px",
    marginTop: "1rem",
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
  },
  avatarCard: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
    padding: "14px",
    borderRadius: "14px",
    border: "1px dashed #E6C9C0",
    background: "linear-gradient(135deg, #FFF7F2 0%, #FDF2F0 100%)",
  },
  avatarPreviewWrap: {
    width: "72px",
    height: "72px",
    borderRadius: "16px",
    background: "#F4E6E2",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "inset 0 0 0 2px rgba(255,255,255,0.7)",
  },
  avatarPreview: {
    width: "100%",
    height: "100%",
    borderRadius: "16px",
    objectFit: "cover" as const,
  },
  avatarPlaceholder: {
    fontSize: "11px",
    color: "#B08A7D",
    textAlign: "center" as const,
    lineHeight: 1.2,
    fontWeight: 600,
  },
  avatarInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    flex: 1,
  },
  avatarTitle: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#3D1E1A",
  },
  avatarSub: {
    fontSize: "11px",
    color: "#9A7B73",
  },
  avatarButton: {
    position: "relative" as const,
    overflow: "hidden",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: "34px",
    padding: "0 14px",
    borderRadius: "10px",
    background: "#C0392B",
    color: "white",
    fontSize: "12px",
    fontWeight: 600,
    border: "none",
    cursor: "pointer",
    width: "fit-content",
    boxShadow: "0 10px 18px rgba(192, 57, 43, 0.25)",
  },
  avatarInput: {
    position: "absolute" as const,
    inset: 0,
    opacity: 0,
    cursor: "pointer",
  },
  avatarName: {
    fontSize: "11px",
    color: "#6B4B41",
  },
  btnBack: {
    height: "44px",
    padding: "0 20px",
    border: "1px solid #E8E2DA",
    borderRadius: "10px",
    background: "transparent",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    color: "#888",
    cursor: "pointer",
  },
  btnNext: {
    flex: 1,
    height: "44px",
    background: "#C0392B",
    color: "white",
    border: "none",
    borderRadius: "10px",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  roleToggleWrapper: {
    marginBottom: "1.5rem",
  },
  roleToggleTrack: {
    position: "relative" as const,
    display: "inline-flex",
    background: "#F0EDE8",
    borderRadius: "12px",
    padding: "4px",
    width: "100%",
    maxWidth: "280px",
    boxShadow: "inset 0 1px 3px rgba(0,0,0,0.06)",
  },
  roleToggleSlider: {
    position: "absolute" as const,
    top: "4px",
    left: "4px",
    width: "calc(50% - 4px)",
    height: "calc(100% - 8px)",
    background: "#C0392B",
    borderRadius: "9px",
    transition: "transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 2px 8px rgba(192, 57, 43, 0.3)",
  },
  roleToggleBtn: {
    position: "relative" as const,
    zIndex: 1,
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    height: "38px",
    border: "none",
    background: "transparent",
    fontFamily: "'DM Sans', sans-serif",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "color 0.3s",
    letterSpacing: "0.3px",
  },
};